[package]
name = "horny"
version = "0.0.0"
description="Unreasonably fast polynomials."
authors = ["Will Brickner <wgbrickner@gmail.com>"]
edition = "2018"
repository="https://github.com/wbrickner/horny"
keywords=["polynomial", "horner", "horners rule"]
license="MIT"

[dependencies]